### ISSUE TITLE
Add a setting to turn on/off the swagger ui

### ISSUE THREAD

**Issue by UNICKCHENG** [UNICKCHENG/Response-Handler#11]
version: 0.2.0

I want to set on or off in the configuration file to decide whether to turn on swagger ui

**Comment by UNICKCHENG** [comment]
You can use the following to set the global settings

```yml
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
```
